- hosts: "{{ host }}"
  vars:
    nginx_dir: "/etc/nginx"
    target_dir: "/usr/share/nginx/html"
    nodejs_dir: "/usr/share/nodejs"
  tasks:
    - name: create directory {{target_dir}}/admin
      file:
        path: "{{target_dir}}/admin"
        state: "{{item}}"
        mode: "0755"
      with_items:
          - absent
          - directory
      tags:
       - admin

    - name: Copy the admin files
      unarchive: 
        src: "/tmp/dist.tar.gz"
        dest: "{{target_dir}}/admin"
        mode: 0755
      tags:
       - admin

    # - name: copy {{nginx_dir}}/conf.d
    #   copy:
    #     src: "./conf/conf.d/"
    #     dest: "{{nginx_dir}}/conf.d/"
    #     # mode: 0644
    #   tags:
    #     - nginx

    # - name: copy {{nginx_dir}}/default.d
    #   copy:
    #     src: "./conf/default.d/"
    #     dest: "{{nginx_dir}}/default.d/"
    #     # mode: 0644
    #   tags:
    #     - nginx

    # - name: restart nginx
    #   service: 
    #     name: nginx
    #     state: reloaded
    #     enabled: yes
    #   tags:
    #     - nginx